// export { default as Beer } from './Beer';
// export { default as Cart } from './Cart';
// export { default as Close } from './Close';
// export { default as Email } from './Email';
// export { default as Facebook } from './Facebook';
// export { default as Fries } from './Fries';
// export { default as Github } from './Github';
// export { default as Home } from './Home';
// export { default as Homeminimal } from './Homeminimal';
// export { default as LinkedIn } from './LinkedIn';
// export { default as MinusCircle } from './MinusCircle';
// export { default as Package } from './Package';
// export { default as Playstation } from './Playstation';
// export { default as PlaystationMin } from './PlaystationMin';
// export { default as PlusCircle } from './PlusCircle';
// export { default as Share } from './Share';
// export { default as Shishsa } from './Shishsa';
// export { default as Snacks } from './Snacks';
// export { default as SodaDrink } from './Soda-Drink';
// export { default as Special } from './Special';
// export { default as Twitter } from './Twitter';
// export { default as Trash } from './Trash';
// export { default as X } from './X';

export { default as BeerIcon } from './Beer';
export { default as CartIcon } from './Cart';
export { default as ChipsCookiesIcon } from './Chips-Cookies';
export { default as ControllerIcon } from './Controller';
export { default as CloseIcon } from './Close';
export { default as DiskoballIcon } from './Diskoball';
export { default as EmailIcon } from './Email';
export { default as FacebookIcon } from './Facebook';
export { default as FriesIcon } from './Fries';
export { default as GithubIcon } from './Github';
export { default as HomeIcon } from './Home';
export { default as HomeminimalIcon } from './Homeminimal';
export { default as InfoIcon } from './Info';
export { default as InstagramColorIcon } from './InstagramColor';
export { default as LinkedInIcon } from './LinkedIn';
export { default as MinusCircleIcon } from './MinusCircle';
export { default as PackageIcon } from './Package';
export { default as PlaystationIcon } from './Playstation';
export { default as PlaystationMinIcon } from './PlaystationMin';
export { default as PlusCircleIcon } from './PlusCircle';
export { default as ShareIcon } from './Share';
export { default as ShishsaIcon } from './Shishsa';
export { default as SnacksIcon } from './Snacks';
export { default as SodaDrink } from './Soda-Drink';
export { default as SpecialIcon } from './Special';
export { default as TwitterIcon } from './Twitter';
export { default as TrashIcon } from './Trash';
export { default as XIcon } from './X';
